
(defun A (x y)
    (cond ((= y 0) 0)
          ((= x 0) (* 2 y))
          ((= y 1) 2)
          (t (A (- x 1)
                   (A x (- y 1))))))
(print (A 1 10))
(print (A 4 2))
(print (A 3 3))

(defun f (n) (A 0 n))
(print (f 2))
(print (f 20))
(print (f 16))
(defun g (n) (A 1 n))
(print (g 2))
(print (g 20))
(print (g 16))
(defun h (n) (A 2 n))
(print (h 1))
(print (h 2))
(print (h 3))
(print (h 4))
(defun k (n) (* 5 n n))
(print (k 1))
(print (k 2))
(print (k 3))
(print (k 4))



